<?php
/**
 * @file
 * Code for the sprowt Fields and Text Formats feature.
 */

include_once 'sprowt_fields_and_text_formats.features.inc';


/**
 * Implements hook_preprocess_HOOK().
 */
function sprowt_fields_and_text_formats_preprocess_field(&$variables)
{
    $element = &$variables['element'];
    if($element['#field_name'] == 'field_icon_file') {
        $items = &$variables['items'];
        foreach($items as &$item) {
            if(strpos($item['#file']->filemime, 'svg') !== false) {
                $svg_html = file_get_contents(drupal_realpath($item['#file']->uri));
                $doc = new DOMDocument();
                $doc->loadXML($svg_html);
                $svg = $doc->getElementsByTagName('svg');
                $svg = $svg->item(0);
                if ($svg->hasAttribute('id')) {
                    $svg->removeAttribute('id');
                }
                $style = $svg->getAttribute('style');

                if (empty($style)) {
                    $style = array();
                } else {
                    $style = explode(';', $style);
                }

                if($svg->hasAttribute('viewBox')) {
                    $viewbox = $svg->getAttribute('viewBox');
                    $viewbox = explode(' ', $viewbox);
                    if(count($viewbox) == 1) {
                        $viewbox = array_pop($viewbox);
                        $viewbox = explode(',', $viewbox);
                    }

                    if(count($viewbox) == 4) {
                        $width = $viewbox[2];
                        $height = $viewbox[3];
                        $svg->setAttribute('width', $width);
                        $svg->setAttribute('height', $height);
                    }
                }

                $style[] = 'min-width:5px';
                $style[] = 'height: auto';
                $style = implode(';', $style) . ';';

                $svg->setAttribute('style', $style);

                $html = $doc->saveHTML($svg);
            }
            else {
                $html = theme('image', array(
                    'path' => $item['#file']->uri
                ));
            }

            if(!empty($item['#path'])) {
                $path = $item['#path']['path'];
                $options = $item['#path']['options'];
                $options['html'] = true;
                $html = l($html, $path, $options);
            }
            $item = array(
                '#type' => 'markup',
                '#markup' => $html
            );
        }
    }
}