<?php

/**
 * Implements hook_menu().
 */
function leadbuilder_dashboard_menu() {
  $items = array();

  $items['admin/dashboard'] = array(
    'title' => t(' Dashboard'),
    'page callback' => 'leadbuilder_dashboard_admin',
    'access callback' => 'leadbuilder_dashboard_access',
    'file' => 'leadbuilder_dashboard.pages.inc',
    'menu_name' => 'management',
    'weight' => -1000,
  );

  return $items;
}

function leadbuilder_dashboard_access() {
  global $user;

  return in_array('administrator', $user->roles);
}
























