<?php
/**
 * @file
 * sprowt_landing_page.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function sprowt_landing_page_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-landing_page-field_footer_paragraph'.
  $field_instances['node-landing_page-field_footer_paragraph'] = array(
    'bundle' => 'landing_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'alt_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 2,
      ),
      'secondary_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_footer_paragraph',
    'label' => 'Footer Paragraph',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'image_break' => -1,
        'landing_page_header_footer' => 'landing_page_header_footer',
        'linked_image' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'image_break' => 5,
        'landing_page_header_footer' => 6,
        'linked_image' => 7,
        'paragraphs' => 8,
        'table' => 9,
        'table_cell' => 10,
        'table_row' => 11,
      ),
      'default_edit_mode' => 'preview',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-landing_page-field_header_paragraph'.
  $field_instances['node-landing_page-field_header_paragraph'] = array(
    'bundle' => 'landing_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'alt_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 1,
      ),
      'secondary_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_header_paragraph',
    'label' => 'Header Paragraph',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'image_break' => -1,
        'landing_page_header_footer' => 'landing_page_header_footer',
        'linked_image' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'image_break' => 5,
        'landing_page_header_footer' => 6,
        'linked_image' => 6,
        'paragraphs' => 7,
        'table' => 8,
        'table_cell' => 9,
        'table_row' => 10,
      ),
      'default_edit_mode' => 'preview',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-landing_page-field_landing_page_content'.
  $field_instances['node-landing_page-field_landing_page_content'] = array(
    'bundle' => 'landing_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'alt_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 0,
      ),
      'secondary_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_landing_page_content',
    'label' => 'Landing Page Content',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'colors' => -1,
        'image_break' => -1,
        'landing_page_features' => -1,
        'landing_page_header_footer' => -1,
        'linked_image' => -1,
        'modal' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'colors' => 15,
        'image_break' => 5,
        'landing_page_features' => 24,
        'landing_page_header_footer' => 17,
        'linked_image' => 6,
        'modal' => -26,
        'paragraphs' => 7,
        'table' => 8,
        'table_cell' => 9,
        'table_row' => 10,
      ),
      'default_edit_mode' => 'preview',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 44,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_colors'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_colors'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 5,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_colors',
    'label' => 'Colors',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'colors' => 'colors',
        'image_break' => -1,
        'landing_page_areas_we_service' => -1,
        'landing_page_benefits' => -1,
        'landing_page_features' => -1,
        'landing_page_header_footer' => -1,
        'landing_page_hero' => -1,
        'landing_page_testimonial' => -1,
        'linked_image' => -1,
        'modal' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'colors' => 5,
        'image_break' => 6,
        'landing_page_areas_we_service' => 7,
        'landing_page_benefits' => 8,
        'landing_page_features' => 9,
        'landing_page_header_footer' => 10,
        'landing_page_hero' => 11,
        'landing_page_testimonial' => 12,
        'linked_image' => 13,
        'modal' => 14,
        'paragraphs' => 15,
        'table' => 16,
        'table_cell' => 17,
        'table_row' => 18,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 11,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_custom_class'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 9,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_header'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_header'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_header',
    'label' => 'Header',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_image'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_image'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'deleted' => 0,
    'description' => 'Either this or the map embed will be shown',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'focal_point_scale_and_crop_460_x_330',
        ),
        'type' => 'image',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_image',
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'multiupload_imagefield_widget',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => 0,
        'insert_class' => '',
        'insert_default' => 'auto',
        'insert_styles' => array(
          'auto' => 'auto',
          'icon_link' => 0,
          'image' => 0,
          'image_affiliation_image' => 0,
          'image_annotated_image' => 0,
          'image_benefits' => 0,
          'image_benefits__front_page_' => 0,
          'image_flexslider_full' => 0,
          'image_flexslider_thumbnail' => 0,
          'image_focal_point_preview' => 0,
          'image_focal_point_scale_and_crop_80x80' => 0,
          'image_focal_point_scale_and_crop_100x100' => 0,
          'image_focal_point_scale_and_crop_185x150' => 0,
          'image_focal_point_scale_and_crop_250x250' => 0,
          'image_focal_point_scale_and_crop_470x400' => 0,
          'image_focal_point_scale_and_crop_500x325' => 0,
          'image_focal_point_scale_and_crop_600x475' => 0,
          'image_focal_point_scale_and_crop_800x600' => 0,
          'image_fresh_light_service' => 0,
          'image_large' => 0,
          'image_markets' => 0,
          'image_medium' => 0,
          'image_menu_icon' => 0,
          'image_package_icon' => 0,
          'image_primary__800x400_' => 0,
          'image_profile' => 0,
          'image_scale_60x60' => 0,
          'image_scale_235' => 0,
          'image_service' => 0,
          'image_service_primary' => 0,
          'image_slideshow_homepage' => 0,
          'image_special_offers_slideshow' => 0,
          'image_thumbnail' => 0,
          'link' => 0,
        ),
        'insert_width' => '',
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_miw',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_intro'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_intro'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_intro',
    'label' => 'Intro',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_label'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_label'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_map_code'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_map_code'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_map_code',
    'label' => 'Map Embed',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_areas_we_service-field_market'.
  $field_instances['paragraphs_item-landing_page_areas_we_service-field_market'] = array(
    'bundle' => 'landing_page_areas_we_service',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_market',
    'label' => 'Markets',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_benefits-field_benefit_style'.
  $field_instances['paragraphs_item-landing_page_benefits-field_benefit_style'] = array(
    'bundle' => 'landing_page_benefits',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_benefit_style',
    'label' => 'Benefit Style',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_benefits-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_benefits-field_custom_class'] = array(
    'bundle' => 'landing_page_benefits',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_benefits-field_embedded_benefits'.
  $field_instances['paragraphs_item-landing_page_benefits-field_embedded_benefits'] = array(
    'bundle' => 'landing_page_benefits',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'landing_page',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_embedded_benefits',
    'label' => 'Embedded Benefits',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'multiple_selects',
      'settings' => array(),
      'type' => 'multiple_selects',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_benefits-field_label'.
  $field_instances['paragraphs_item-landing_page_benefits-field_label'] = array(
    'bundle' => 'landing_page_benefits',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'hidden',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_button'.
  $field_instances['paragraphs_item-landing_page_features-field_button'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_button',
    'label' => 'Button',
    'required' => 0,
    'settings' => array(
      'absolute_url' => 1,
      'attributes' => array(
        'class' => 'button',
        'configurable_class' => 0,
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'user',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'required',
      'title_label_use_field_label' => 0,
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_features-field_custom_class'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_features_list'.
  $field_instances['paragraphs_item-landing_page_features-field_features_list'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_features_list',
    'label' => 'Features',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_header'.
  $field_instances['paragraphs_item-landing_page_features-field_header'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_header',
    'label' => 'Header',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_intro'.
  $field_instances['paragraphs_item-landing_page_features-field_intro'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_intro',
    'label' => 'Intro',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_features-field_label'.
  $field_instances['paragraphs_item-landing_page_features-field_label'] = array(
    'bundle' => 'landing_page_features',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_header_footer-field_cta_text'.
  $field_instances['paragraphs_item-landing_page_header_footer-field_cta_text'] = array(
    'bundle' => 'landing_page_header_footer',
    'default_value' => array(
      0 => array(
        'value' => 'Request My <strong>FREE</strong> Inspection! [phone-number]',
        'format' => 'filtered_html',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_cta_text',
    'label' => 'CTA Text',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_header_footer-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_header_footer-field_custom_class'] = array(
    'bundle' => 'landing_page_header_footer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_header_footer-field_label'.
  $field_instances['paragraphs_item-landing_page_header_footer-field_label'] = array(
    'bundle' => 'landing_page_header_footer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_header_footer-field_landing_page_logo'.
  $field_instances['paragraphs_item-landing_page_header_footer-field_landing_page_logo'] = array(
    'bundle' => 'landing_page_header_footer',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_landing_page_logo',
    'label' => 'Landing Page Logo',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'multiupload_imagefield_widget',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => 0,
        'insert_class' => '',
        'insert_default' => 'auto',
        'insert_styles' => array(
          'auto' => 'auto',
          'icon_link' => 0,
          'image' => 0,
          'image_affiliation_image' => 0,
          'image_annotated_image' => 0,
          'image_benefits' => 0,
          'image_benefits__front_page_' => 0,
          'image_flexslider_full' => 0,
          'image_flexslider_thumbnail' => 0,
          'image_focal_point_preview' => 0,
          'image_focal_point_scale_and_crop_80x80' => 0,
          'image_focal_point_scale_and_crop_100x100' => 0,
          'image_focal_point_scale_and_crop_185x150' => 0,
          'image_focal_point_scale_and_crop_250x250' => 0,
          'image_focal_point_scale_and_crop_470x400' => 0,
          'image_focal_point_scale_and_crop_500x325' => 0,
          'image_focal_point_scale_and_crop_600x475' => 0,
          'image_focal_point_scale_and_crop_800x600' => 0,
          'image_fresh_light_service' => 0,
          'image_large' => 0,
          'image_markets' => 0,
          'image_medium' => 0,
          'image_menu_icon' => 0,
          'image_package_icon' => 0,
          'image_primary__800x400_' => 0,
          'image_profile' => 0,
          'image_scale_60x60' => 0,
          'image_scale_235' => 0,
          'image_service' => 0,
          'image_service_primary' => 0,
          'image_slideshow_homepage' => 0,
          'image_special_offers_slideshow' => 0,
          'image_thumbnail' => 0,
          'link' => 0,
        ),
        'insert_width' => '',
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_miw',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_hero-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_hero-field_custom_class'] = array(
    'bundle' => 'landing_page_hero',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_hero-field_display_title'.
  $field_instances['paragraphs_item-landing_page_hero-field_display_title'] = array(
    'bundle' => 'landing_page_hero',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_display_title',
    'label' => 'Title',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_hero-field_header_paragraph'.
  $field_instances['paragraphs_item-landing_page_hero-field_header_paragraph'] = array(
    'bundle' => 'landing_page_hero',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_header_paragraph',
    'label' => 'Hero Paragraph',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'colors' => -1,
        'image_break' => -1,
        'landing_page_features' => -1,
        'landing_page_header_footer' => -1,
        'landing_page_hero' => -1,
        'linked_image' => -1,
        'modal' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'colors' => 5,
        'image_break' => 6,
        'landing_page_features' => 7,
        'landing_page_header_footer' => 8,
        'landing_page_hero' => 9,
        'linked_image' => 10,
        'modal' => 11,
        'paragraphs' => 12,
        'table' => 13,
        'table_cell' => 14,
        'table_row' => 15,
      ),
      'default_edit_mode' => 'preview',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'paragraphs_item-landing_page_hero-field_intro'.
  $field_instances['paragraphs_item-landing_page_hero-field_intro'] = array(
    'bundle' => 'landing_page_hero',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_intro',
    'label' => 'Intro',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'paragraphs_item-landing_page_hero-field_label'.
  $field_instances['paragraphs_item-landing_page_hero-field_label'] = array(
    'bundle' => 'landing_page_hero',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_package-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_package-field_custom_class'] = array(
    'bundle' => 'landing_page_package',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_package-field_package'.
  $field_instances['paragraphs_item-landing_page_package-field_package'] = array(
    'bundle' => 'landing_page_package',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'landing_page',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'entityreference',
        'settings' => array(
          'bypass_access' => 0,
          'link' => 1,
        ),
        'type' => 'entityreference_label',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_package',
    'label' => 'Package',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_packages-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_packages-field_custom_class'] = array(
    'bundle' => 'landing_page_packages',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_packages-field_label'.
  $field_instances['paragraphs_item-landing_page_packages-field_label'] = array(
    'bundle' => 'landing_page_packages',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_packages-field_lp_packages'.
  $field_instances['paragraphs_item-landing_page_packages-field_lp_packages'] = array(
    'bundle' => 'landing_page_packages',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_lp_packages',
    'label' => 'Packages',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'colors' => -1,
        'image_break' => -1,
        'landing_page_areas_we_service' => -1,
        'landing_page_benefits' => -1,
        'landing_page_features' => -1,
        'landing_page_header_footer' => -1,
        'landing_page_hero' => -1,
        'landing_page_package' => 'landing_page_package',
        'landing_page_packages' => -1,
        'landing_page_special_offer' => -1,
        'landing_page_testimonial' => -1,
        'linked_image' => -1,
        'modal' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'colors' => 5,
        'image_break' => 6,
        'landing_page_areas_we_service' => 7,
        'landing_page_benefits' => 8,
        'landing_page_features' => 9,
        'landing_page_header_footer' => 10,
        'landing_page_hero' => 11,
        'landing_page_package' => 12,
        'landing_page_packages' => 13,
        'landing_page_special_offer' => 14,
        'landing_page_testimonial' => 15,
        'linked_image' => 16,
        'modal' => 17,
        'paragraphs' => 18,
        'table' => 19,
        'table_cell' => 20,
        'table_row' => 21,
      ),
      'default_edit_mode' => 'preview',
      'title' => 'Package',
      'title_multiple' => 'Packages',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_big_text'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_big_text'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_big_text',
    'label' => 'Big Text',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_colors'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_colors'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 5,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_colors',
    'label' => 'Colors',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'button',
      'allowed_bundles' => array(
        'annotated_image' => -1,
        'block_embed' => -1,
        'body' => -1,
        'colors' => 'colors',
        'image_break' => -1,
        'landing_page_areas_we_service' => -1,
        'landing_page_benefits' => -1,
        'landing_page_features' => -1,
        'landing_page_header_footer' => -1,
        'landing_page_hero' => -1,
        'landing_page_special_offer' => -1,
        'landing_page_testimonial' => -1,
        'linked_image' => -1,
        'modal' => -1,
        'paragraphs' => -1,
        'table' => -1,
        'table_cell' => -1,
        'table_row' => -1,
      ),
      'bundle_weights' => array(
        'annotated_image' => 2,
        'block_embed' => 3,
        'body' => 4,
        'colors' => 5,
        'image_break' => 6,
        'landing_page_areas_we_service' => 7,
        'landing_page_benefits' => 8,
        'landing_page_features' => 9,
        'landing_page_header_footer' => 10,
        'landing_page_hero' => 11,
        'landing_page_special_offer' => 12,
        'landing_page_testimonial' => 13,
        'linked_image' => 14,
        'modal' => 15,
        'paragraphs' => 16,
        'table' => 17,
        'table_cell' => 18,
        'table_row' => 19,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_custom_class'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_display_title'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_display_title'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => array(
      0 => array(
        'value' => 'Special Offer',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_display_title',
    'label' => 'Title',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_label'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_label'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_prefix'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_prefix'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_prefix',
    'label' => 'Prefix',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_suffix'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_suffix'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_suffix',
    'label' => 'Suffix',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_special_offer-field_two_buttons'.
  $field_instances['paragraphs_item-landing_page_special_offer-field_two_buttons'] = array(
    'bundle' => 'landing_page_special_offer',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 4,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_two_buttons',
    'label' => 'Buttons',
    'required' => 0,
    'settings' => array(
      'absolute_url' => 1,
      'attributes' => array(
        'class' => 'button',
        'configurable_class' => 0,
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'user',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'optional',
      'title_label_use_field_label' => 0,
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_testimonial-field_custom_class'.
  $field_instances['paragraphs_item-landing_page_testimonial-field_custom_class'] = array(
    'bundle' => 'landing_page_testimonial',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_custom_class',
    'label' => 'Custom Class',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_testimonial-field_embedded_testimonial'.
  $field_instances['paragraphs_item-landing_page_testimonial-field_embedded_testimonial'] = array(
    'bundle' => 'landing_page_testimonial',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'One of these will randomly load on page load.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_embedded_testimonial',
    'label' => 'Embedded Testimonial',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'multiple_selects',
      'settings' => array(),
      'type' => 'multiple_selects',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_testimonial-field_header'.
  $field_instances['paragraphs_item-landing_page_testimonial-field_header'] = array(
    'bundle' => 'landing_page_testimonial',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_header',
    'label' => 'Header',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'paragraphs_item-landing_page_testimonial-field_label'.
  $field_instances['paragraphs_item-landing_page_testimonial-field_label'] = array(
    'bundle' => 'landing_page_testimonial',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'inline',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 0,
          'trim_length' => 600,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'field_name' => 'field_label',
    'label' => 'Label',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'show_token_tree' => 0,
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Benefit Style');
  t('Big Text');
  t('Button');
  t('Buttons');
  t('CTA Text');
  t('Colors');
  t('Custom Class');
  t('Either this or the map embed will be shown');
  t('Embedded Benefits');
  t('Embedded Testimonial');
  t('Features');
  t('Footer Paragraph');
  t('Header');
  t('Header Paragraph');
  t('Hero Paragraph');
  t('Image');
  t('Intro');
  t('Label');
  t('Landing Page Content');
  t('Landing Page Logo');
  t('Map Embed');
  t('Markets');
  t('One of these will randomly load on page load.');
  t('Package');
  t('Packages');
  t('Prefix');
  t('Suffix');
  t('Title');

  return $field_instances;
}
