<?php
/**
 * @file
 * sprowt_concerns.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function sprowt_concerns_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_concern_steps'.
  $field_bases['field_concern_steps'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_concern_steps',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_concern_treatment'.
  $field_bases['field_concern_treatment'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_concern_treatment',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  return $field_bases;
}
