<?php

function pantheon_redirect_boot(){
    $base_url = variable_get('pantheon_redirect_base_url', false);
    if(!empty($base_url)) {
        if(strpos($base_url, 'https:') !== false) {
            if (isset($_SERVER['PANTHEON_ENVIRONMENT']) &&
                ($_SERVER['HTTPS'] === 'OFF') &&
                // Check if Drupal or WordPress is running via command line
                (php_sapi_name() != "cli")) {
                if (!isset($_SERVER['HTTP_X_SSL']) ||
                    (isset($_SERVER['HTTP_X_SSL']) && $_SERVER['HTTP_X_SSL'] != 'ON')) {
                    if (isset($_SERVER['PANTHEON_ENVIRONMENT']) &&
                        ($_SERVER['PANTHEON_ENVIRONMENT'] === 'live') &&
                        // Check if Drupal or WordPress is running via command line
                        (php_sapi_name() != "cli")) {
                        if('https://' . $_SERVER['HTTP_HOST'] != $base_url) {
                            if (strpos($_SERVER['HTTP_HOST'], 'pantheonsite.io') === FALSE) {
                                header('HTTP/1.0 301 Moved Permanently');
                                header('Location: ' . $base_url . $_SERVER['REQUEST_URI']);
                                exit();
                            }
                        }
                    }
                }
            }
        }
        else {
            if (isset($_SERVER['PANTHEON_ENVIRONMENT']) &&
                ($_SERVER['PANTHEON_ENVIRONMENT'] === 'live') &&
                // Check if Drupal or WordPress is running via command line
                (php_sapi_name() != "cli")) {
                if('http://' . $_SERVER['HTTP_HOST'] != $base_url) {
                    if (strpos($_SERVER['HTTP_HOST'], 'pantheonsite.io') === FALSE) {
                        header('HTTP/1.0 301 Moved Permanently');
                        header('Location: ' . $base_url . $_SERVER['REQUEST_URI']);
                        exit();
                    }
                }
            }
        }
    }
}

function pantheon_redirect_menu() {
    $items = array();
    $items['admin/config/system/pantheon-redirect'] = array(
        'title' => 'Pantheon Redirect Settings',
        'description' => 'Set the URL to redirect to here',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pantheon_redirect_settings_form'),
        'access arguments' => array('administer site configuration'),
    );
    
    return $items;
}

function pantheon_redirect_settings_form() {
    $form = array();
    
    $form['pantheon_redirect_base_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Redirect URL'),
        '#description' => t('Base URL the site will redirect to. This URL will always be the base URL unless the site is not in Pantheon\'s live environment or is using a *.pantheonsite.io URL'),
        '#default_value' => variable_get('pantheon_redirect_base_url', '')
    );
    
    $form['#validate'][] = 'pantheon_redirect_settings_form_validate';
    return system_settings_form($form);
}

function pantheon_redirect_settings_form_validate(&$form, &$form_state) {
    $values = $form_state['values'];
    $url = $values['pantheon_redirect_base_url'];
    if(!empty($url) && strpos($url, 'http:') !== 0 && strpos($url, 'https:') !== 0) {
        form_error($form['pantheon_redirect_base_url'], t('Please use a valid URL that begins with http or https'));
    }
}