<?php

/**
 * Implements hook_menu().
 */
function sprowt_noindex_menu() {
    $items = [];
    $items['admin/config/search/sprowt-noindex'] = [
        'title' => 'Sprowt No Index',
        'description' => 'Administer no index settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['_sprowt_noindex_admin_form'],
        'access arguments' => ['administer nodes']
    ];

    return $items;
}


function _sprowt_noindex_admin_form($form, &$form_state) {
    drupal_set_title('Administer No Index Settings');
    $paths = variable_get('sprowt_noindex_paths', []);
    $form['sprowt_noindex_paths'] = [
        '#type' => 'textarea',
        '#title' => 'Paths',
        '#description' => 'Add paths you would like to have no indexed. Paths should be separated by new lines or spaces. Paths should be in the drupal format. Paths can use the * wildcard.',
        '#default_value' => implode("\n", $paths)
    ];

    $form['actions'] = [
        'submit' => [
            '#type' => 'submit',
            '#value' => 'Save',
            '#submit' => ['_sprowt_noindex_admin_form_submit']
        ]
    ];

    return $form;
}

function _sprowt_noindex_admin_form_submit($form, &$form_state) {
    $values = $form_state['values'];
    if(!empty($values['sprowt_noindex_paths'])) {
        $input = preg_split('/\s/', $values['sprowt_noindex_paths']);
        $paths = [];
        foreach($input as $path) {
            if(!empty($path)) {
                $paths[] = trim($path);
            }
        }
        if(!empty($paths)) {
            variable_set('sprowt_noindex_paths', $paths);
        }
        else {
            variable_del('sprowt_noindex_paths');
        }
    }
    else {
        variable_del('sprowt_noindex_paths');
    }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function sprowt_noindex_preprocess_html(&$variables) {
    $paths = variable_get('sprowt_noindex_paths', []);
    $path = strtolower(drupal_get_path_alias($_GET['q']));
    $page_match = drupal_match_path($path, implode("\n", $paths));
    if ($path != $_GET['q']) {
        $page_match = $page_match || drupal_match_path($_GET['q'], implode("\n", $paths));
    }
    if($page_match) {
        $noIndex = [
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => [
                'name' => 'robots',
                'content' => 'noindex'
            ],
            '#prefix' => '<!-- no indexed by sprowt noindex -->' . "\n"
        ];

        drupal_add_html_head($noIndex, 'sprowt_noindex_meta');
    }
}
