<?php
/**
 * @file
 * Code for the Sprowt Learning Center feature.
 */

include_once 'sprowt_learning_center.features.inc';

/**
 * Implements hook_theme().
 */
function sprowt_learning_center_theme() {
  return array(
    'views-view--learning-center' => array(
      'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views_view_unformatted__learning_center__learning_list',
      'path' => drupal_get_path('module', 'sprowt_learning_center'),
    ),
  );
}
