<?php
/**
 * @file
 * Code for the Sprowt Learning Center feature.
 */

include_once 'sprowt_learning_center.features.inc';

/**
 * Implements hook_theme().
 */
function sprowt_learning_center_theme() {
  return array(
    'views_view_unformatted__learning_center__learning_list' => array (
        'template' => 'views-view-unformatted--learning-center--learning-list',
        'path' => drupal_get_path('module', 'sprowt_learning_center') . '/templates',
        'variables' =>
            array (
                'view' => NULL,
                'options' => NULL,
                'rows' => NULL,
                'title' => NULL,
            ),
        'base hook' => 'views_view_unformatted',
    ),
  );
}
