<?php
/**
 * @file
 * Code for the Sprowt Paragraphs feature.
 */

include_once 'sprowt_paragraphs.features.inc';


/**
 * Implements hook_theme().
 */
function sprowt_paragraphs_theme($existing, $type, $theme, $path)
{
    return array(
        'field__field_header__paragraphs_item' => array (
            'template' => 'field--field-header--paragraphs-item',
            'path' => $path . '/theme',
            'base hook' => 'field',
        ),
    );
}

/**
 * Implements hook_preprocess_entity().
 */
function sprowt_paragraphs_preprocess_entity(&$variables)
{
    if ($variables['entity_type'] == 'paragraphs_item') {
        $custom_class = field_get_items('paragraphs_item', $variables['elements']['#entity'], 'field_custom_class');
        if(!empty($custom_class)) {
            foreach($custom_class as $class) {
                $classes = explode(' ', $class['value']);
                $new_classes_array = array_merge($variables['classes_array'], $classes);
                $variables['classes_array'] = $new_classes_array;
                $variables['attributes_array']['class'] = $new_classes_array;
            }
        }
    }
}