<?php
/**
 * @file
 * Code for the Sprowt Paragraphs feature.
 */

include_once 'sprowt_paragraphs.features.inc';


/**
 * Implements hook_theme().
 */
function sprowt_paragraphs_theme($existing, $type, $theme, $path)
{
    return array(
        'field__field_header__paragraphs_item' => array (
            'template' => 'field--field-header--paragraphs-item',
            'path' => $path . '/theme',
            'base hook' => 'field',
        ),
    );
}