<?php

/**
 * Implements hook_menu().
 */
function paragraphs_edit_menu() {
    global $user;
    $items = array();
    
    $items['paragraphs-edit/%paragraphs_item'] = array(
        'title' => 'Edit Paragraph',
        'page callback' => 'paragraphs_edit_page',
        'page arguments' => array(1),
        'access callback' => 'paragraphs_paragraphs_item_access',
        'access arguments' => array(1, 'update', $user),
    );
    
    return $items;
}

function paragraphs_edit_page($paragraph) {
    $form = drupal_get_form('_paragraphs_edit_form', $paragraph);
    return $form;
}

function _paragraphs_edit_form($form, $form_state, $paragraph) {
    $form = array();
    $form['#paragraph'] = $paragraph;
    field_attach_form('paragraphs_item', $paragraph, $form, $form_state, entity_language('paragraphs_item', $paragraph));
    $form['#after_build'][] = 'paragraphs_field_widget_embed_delay_required_validation';
    $actions = array(
        '#type' => 'container',
        '#weight' => 99
    );
    
    $actions['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Save',
    );
    
    $form['paragraphs_edit_actions'] = $actions;
    $form['#submit'] = array('_paragraphs_edit_form_submit');
    $form['#validate'] = array('_paragraphs_edit_form_validate');
    
    return $form;
}

function _paragraphs_edit_form_validate(&$form, &$form_state) {
    $paragraph = $form['#paragraph'];
    field_attach_form_validate('paragraphs_item', $paragraph, $form, $form_state);
    $form['#paragraph'] = $paragraph;
}

function _paragraphs_edit_form_submit(&$form, &$form_state) {
    $paragraph = $form['#paragraph'];
    field_attach_submit('paragraphs_item', $paragraph, $form, $form_state);
    $paragraph->save();
}

/**
 * Implements hook_custom_theme().
 */
function paragraphs_edit_custom_theme() {
    if(arg(0) == 'paragraphs-edit') {
        return variable_get('admin_theme');
    }
}