<?php
/**
 * @file
 * sprowt_ebooking_features.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function sprowt_ebooking_features_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-webform-field_ebooking'.
  $field_instances['node-webform-field_ebooking'] = array(
    'bundle' => 'webform',
    'default_value' => array(
      0 => array(
        'value' => 'no',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'alt_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'secondary_teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ebooking',
    'label' => 'eBooking',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => -2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('eBooking');

  return $field_instances;
}
